-- fabtoolreadiness schema
-- Re-runnable: drops everything it creates first.

DROP TABLE IF EXISTS training_completions CASCADE;
DROP TABLE IF EXISTS tech_certifications CASCADE;
DROP TABLE IF EXISTS certifications CASCADE;
DROP TABLE IF EXISTS technicians CASCADE;
DROP TABLE IF EXISTS stock_movements CASCADE;
DROP TABLE IF EXISTS inventory CASCADE;
DROP TABLE IF EXISTS tool_bom CASCADE;
DROP TABLE IF EXISTS parts CASCADE;
DROP TABLE IF EXISTS tools CASCADE;
DROP TABLE IF EXISTS sites CASCADE;

-- ---------------------------------------------------------------------------
-- Lookups / master data
-- ---------------------------------------------------------------------------

CREATE TABLE sites (
    site_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_code  VARCHAR(10)  NOT NULL UNIQUE CHECK (site_code <> ''),
    site_name  VARCHAR(100) NOT NULL CHECK (site_name <> ''),
    region     VARCHAR(20)  NOT NULL CHECK (region IN ('Americas', 'Europe', 'Asia'))
);

CREATE TABLE tools (
    tool_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id       INT         NOT NULL REFERENCES sites (site_id),
    tool_code     VARCHAR(20) NOT NULL UNIQUE CHECK (tool_code <> ''),
    tool_type     VARCHAR(50) NOT NULL CHECK (tool_type <> ''),
    process_area  VARCHAR(50) NOT NULL CHECK (process_area <> ''),
    install_date  DATE        NOT NULL,
    criticality   SMALLINT    NOT NULL CHECK (criticality BETWEEN 1 AND 5)
);

CREATE INDEX idx_tools_site_id      ON tools (site_id);
CREATE INDEX idx_tools_tool_type    ON tools (tool_type);
CREATE INDEX idx_tools_install_date ON tools (install_date);

CREATE TABLE parts (
    part_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_number     VARCHAR(30)  NOT NULL UNIQUE CHECK (part_number <> ''),
    description     VARCHAR(200) NOT NULL CHECK (description <> ''),
    unit_cost       NUMERIC(10, 2) NOT NULL CHECK (unit_cost >= 0),
    lead_time_days  INT            NOT NULL CHECK (lead_time_days >= 0),
    is_consumable   BOOLEAN        NOT NULL DEFAULT FALSE
);

-- ---------------------------------------------------------------------------
-- Bill of material per tool
-- ---------------------------------------------------------------------------

CREATE TABLE tool_bom (
    tool_id      INT           NOT NULL REFERENCES tools (tool_id),
    part_id      INT           NOT NULL REFERENCES parts (part_id),
    qty_per_tool NUMERIC(8, 2) NOT NULL CHECK (qty_per_tool > 0),
    PRIMARY KEY (tool_id, part_id)
);

CREATE INDEX idx_tool_bom_part_id ON tool_bom (part_id);

-- ---------------------------------------------------------------------------
-- Spare-parts inventory per site
-- ---------------------------------------------------------------------------

CREATE TABLE inventory (
    site_id            INT   NOT NULL REFERENCES sites (site_id),
    part_id            INT   NOT NULL REFERENCES parts (part_id),
    on_hand_qty        INT   NOT NULL CHECK (on_hand_qty >= 0),
    reorder_point      INT   NOT NULL CHECK (reorder_point >= 0),
    safety_stock       INT   NOT NULL CHECK (safety_stock >= 0),
    last_counted_date  DATE  NOT NULL,
    PRIMARY KEY (site_id, part_id)
);

CREATE INDEX idx_inventory_part_id          ON inventory (part_id);
CREATE INDEX idx_inventory_last_counted     ON inventory (last_counted_date);

-- ---------------------------------------------------------------------------
-- Stock movements
-- ---------------------------------------------------------------------------

CREATE TABLE stock_movements (
    movement_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id         INT  NOT NULL REFERENCES sites (site_id),
    part_id         INT  NOT NULL REFERENCES parts (part_id),
    tool_id         INT  NULL REFERENCES tools (tool_id),
    movement_date   DATE NOT NULL,
    qty_delta       INT  NOT NULL CHECK (qty_delta <> 0),
    movement_type   VARCHAR(20) NOT NULL
        CHECK (movement_type IN ('receipt', 'consumption', 'adjustment', 'scrap'))
);

CREATE INDEX idx_stock_movements_date ON stock_movements (movement_date);
CREATE INDEX idx_stock_movements_site ON stock_movements (site_id);
CREATE INDEX idx_stock_movements_part ON stock_movements (part_id);
CREATE INDEX idx_stock_movements_tool ON stock_movements (tool_id);

-- ---------------------------------------------------------------------------
-- Technicians, certifications, coverage
-- ---------------------------------------------------------------------------

CREATE TABLE technicians (
    tech_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id       INT         NOT NULL REFERENCES sites (site_id),
    employee_code VARCHAR(20) NOT NULL UNIQUE CHECK (employee_code <> ''),
    hire_date     DATE        NOT NULL,
    shift         CHAR(1)     NOT NULL CHECK (shift IN ('A', 'B', 'C', 'D')),
    is_active     BOOLEAN     NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_technicians_site_id ON technicians (site_id);
CREATE INDEX idx_technicians_shift   ON technicians (shift);

CREATE TABLE certifications (
    cert_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cert_code       VARCHAR(20)  NOT NULL UNIQUE CHECK (cert_code <> ''),
    cert_name       VARCHAR(100) NOT NULL CHECK (cert_name <> ''),
    tool_type       VARCHAR(50)  NOT NULL CHECK (tool_type <> ''),
    validity_months INT          NOT NULL CHECK (validity_months > 0)
);

CREATE INDEX idx_certifications_tool_type ON certifications (tool_type);

CREATE TABLE tech_certifications (
    tech_id       INT         NOT NULL REFERENCES technicians (tech_id),
    cert_id       INT         NOT NULL REFERENCES certifications (cert_id),
    earned_date   DATE        NULL,
    expires_date  DATE        NULL,
    status        VARCHAR(20) NOT NULL
        CHECK (status IN ('active', 'expired', 'in_progress')),
    PRIMARY KEY (tech_id, cert_id),
    CHECK (
        (status = 'in_progress' AND earned_date IS NULL AND expires_date IS NULL)
        OR
        (status <> 'in_progress'
         AND earned_date IS NOT NULL
         AND expires_date IS NOT NULL
         AND expires_date > earned_date)
    )
);

CREATE INDEX idx_tech_certifications_cert_id ON tech_certifications (cert_id);
CREATE INDEX idx_tech_certifications_expiry  ON tech_certifications (expires_date);

CREATE TABLE training_completions (
    completion_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tech_id        INT  NOT NULL REFERENCES technicians (tech_id),
    cert_id        INT  NOT NULL REFERENCES certifications (cert_id),
    enrolled_date  DATE NOT NULL,
    completed_date DATE NULL,
    hours_spent    NUMERIC(6, 1) NULL CHECK (hours_spent IS NULL OR hours_spent >= 0),
    CHECK (completed_date IS NULL OR completed_date >= enrolled_date)
);

CREATE INDEX idx_training_completions_tech  ON training_completions (tech_id);
CREATE INDEX idx_training_completions_cert  ON training_completions (cert_id);
CREATE INDEX idx_training_completions_dates ON training_completions (enrolled_date, completed_date);
